---
apiVersion: acme.com/v1
kind: XAcmeDatabase
metadata:
  name: acme-db-prod
spec:
  environment: prod
  storageGB: 100
  writeConnectionSecretToRef:
    name: acme-db-prod-conn
    namespace: default
